In [52]:
import pandas as pd
import numpy as np

In [134]:
url = "/Users/davidguenoun/Downloads/ML_spotify_data.csv"
df = pd.read_csv(url)

In [135]:
i_really_love_you_girl = df.iloc[3602:3603]

In [101]:
from sklearn.neighbors import KNeighborsRegressor
# Define X and y
X = df.drop(columns = ["name", "artists"]) #we drop the non numerical values
y = df["tempo"] #we are concerned about similarities between features : so we can choose any feature for y

In [102]:
knn_model = KNeighborsRegressor().fit(X,y)

In [ ]:
# Return the distances and index of the 5 closest points

In [104]:
knn_model.kneighbors(i_really_love_you_girl.drop(columns=['name','artists']),n_neighbors=5)

(array([[0.        , 1.67299152, 2.64590594, 3.17620249, 3.46731355]]),
 array([[3602, 2412,  485,  402, 2591]]))

In [ ]:
# Return the index of the 3rd closest points

In [105]:
knn_model.kneighbors(i_really_love_you_girl.drop(columns=['name','artists']),n_neighbors=5)[1]

array([[3602, 2412,  485,  402, 2591]])

# Create a Playlist of Ten songs

In [110]:
# Pass song to model, ask for 11 closest points, and unpack the corresponding indices to a list
ind_list = list(knn_model.kneighbors(i_really_love_you_girl.drop(columns=['name','artists']),n_neighbors=11)[1][0])
ind_list

[3602, 2412, 485, 402, 2591, 3318, 3056, 3483, 2550, 953, 2808]

In [ ]:
#we pass 11 songs because the first one 

In [111]:
# Filter original dataframe with indices list and sort by tempo
df.iloc[ind_list, :].sort_values(by="tempo")

name                               artists  \
2550                            Alyson                  ['Rick Springfield']   
2808                      All Fired Up                           ['Fastway']   
402                           My Stars                      ['Alice Cooper']   
3483                 All Day All Night    ['Bobby Brown', 'Louil Silas Jr.']   
3318  The Homecoming Queen's Got a Gun                       ['Julie Brown']   
485    Santa's Coming Down the Chimney              ['The Golden Orchestra']   
2412              Write Your Own Songs  ['Waylon Jennings', 'Willie Nelson']   
3602            I Really Love You Girl                       ['Bobby Brown']   
2591                       Dying World                         ['Subhumans']   
953    He Was in Heaven Before He Died                        ['John Prine']   
3056               Scarred But Smarter                    ['Drivin N Cryin']   

      popularity  danceability  valence  energy  explicit  key  liveness  \
2550          22         0.533    0.806   0.708         0    2    0.2520   
2808          25         0.379    0.226   0.932         0    2    0.3670   
402           25         0.211    0.522   0.832         0    2    0.4130   
3483          24         0.734    0.812   0.533         0    0    0.0486   
3318          25         0.402    0.381   0.764         0    2    0.1380   
485           22         0.534    0.795   0.339         0    2    0.2980   
2412          22         0.534    0.451   0.303         0    2    0.0990   
3602          23         0.611    0.668   0.548         0    2    0.1450   
2591          22         0.158    0.338   0.889         0    4    0.1710   
953           21         0.361    0.579   0.251         0    0    0.1450   
3056          22         0.418    0.416   0.965         0    2    0.0498   

      loudness  speechiness    tempo  
2550   -13.389       0.0329  163.157  
2808   -11.194       0.0373  163.964  
402    -11.948       0.0529  165.149  
3483   -10.552       0.1010  165.475  
3318   -10.581       0.1110  166.029  
485    -15.406       0.0559  166.045  
2412   -14.532       0.0492  166.978  
3602   -13.248       0.0384  167.165  
2591   -11.878       0.0709  169.336  
953    -15.083       0.0309  169.710  
3056   -10.949       0.3060  169.984

# Create a function that returns the 5 most similar songs

In [114]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor

In [137]:
url = "/Users/davidguenoun/Downloads/ML_spotify_data.csv"
df = pd.read_csv(url)
df

name  \
0                 We're For The Dark - Remastered 2010   
1                          Sixty Years On - Piano Demo   
2                              Got to Find Another Way   
3     Feelin' Alright - Live At The Fillmore East/1970   
4                                     Caravan - Take 7   
...                                                ...   
9995                                             China   
9996                       Halloweenie III: Seven Days   
9997                                               AYA   
9998                                          Darkness   
9999                   Billetes Azules (with J Balvin)   

                                                artists  popularity  \
0                                         ['Badfinger']          22   
1                                        ['Elton John']          25   
2                                     ['The Guess Who']          21   
3                                        ['Joe Cocker']          22   
4                                      ['Van Morrison']          23   
...                                                 ...         ...   
9995  ['Anuel AA', 'Daddy Yankee', 'KAROL G', 'Ozuna...          72   
9996                                       ['Ashnikko']          68   
9997                                        ['MAMAMOO']          76   
9998                                         ['Eminem']          70   
9999                              ['KEVVO', 'J Balvin']          74   

      danceability  valence  energy  explicit  key  liveness  loudness  \
0            0.678    0.559   0.432         0    3    0.0727   -12.696   
1            0.456    0.259   0.368         0    6    0.1560   -10.692   
2            0.433    0.833   0.724         0    0    0.1700    -9.803   
3            0.436    0.870   0.914         0    5    0.8550    -6.955   
4            0.669    0.564   0.412         0    7    0.4010   -13.095   
...            ...      ...     ...       ...  ...       ...       ...   
9995         0.786    0.608   0.808         0    7    0.0822    -3.702   
9996         0.717    0.734   0.753         0    7    0.1010    -6.020   
9997         0.634    0.637   0.858         0    4    0.2580    -2.226   
9998         0.671    0.195   0.623         1    2    0.6430    -7.161   
9999         0.856    0.642   0.721         1    7    0.1820    -4.928   

      speechiness    tempo  
0          0.0334  117.674  
1          0.0280  143.783  
2          0.0378   84.341  
3          0.0610  174.005  
4          0.0679   78.716  
...           ...      ...  
9995       0.0881  105.029  
9996       0.0605  137.936  
9997       0.0809   91.688  
9998       0.3080   75.055  
9999       0.1080   94.991  

[10000 rows x 12 columns]

In [149]:
def most_similar_songs(song):
    X = df.drop(columns = ["name", "artists"])
    y = df["tempo"]
    knn_model = KNeighborsRegressor().fit(X,y)
    song = df.loc[df['name'] == song]
    ind_list = list(knn_model.kneighbors(song.drop(columns=['name','artists']),n_neighbors=6)[1][0])
    list_song = df.iloc[ind_list, :]["name"].tolist()
    return list_song[1:]

most_similar_songs("Working Without A Net")


["He'll Have to Go",
 "I'm Never Gonna Tell It",
 "Thank God It's Not Christmas",
 'Feelings',
 'Bad Side Of The Moon']