In [10]:
import requests
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer


In [11]:
ls


Davis-Pris API.ipynb               Untitled.ipynb
Priscilla - exploring Regex.ipynb  renato_call_data.ipynb
Priscilla -API fetching .ipynb


In [32]:
full_data_merged = pd.read_csv("./../raw_data/full_data_merged.csv")
full_data_merged

movie_id  Year_x                 Name      mean  count  \
0             1  2003.0      Dinosaur Planet  3.749543    547   
1             3  1997.0            Character  3.641153   2012   
2             6  1997.0                 Sick  3.084396   1019   
3             7  1992.0                8 Man  2.129032     93   
4            10  2001.0              Fighter  3.180723    249   
...         ...     ...                  ...       ...    ...   
12375     17763  1978.0            Interiors  3.411855   1957   
12376     17764  1998.0  Shakespeare in Love  3.867112  64957   
12377     17768  2000.0                Epoch  2.839207   1362   
12378     17769  2003.0          The Company  2.498592   6749   
12379     17770  2003.0         Alien Hunter  2.816504    921   

                     Title Year_y      Rated     Released  Runtime  ...  \
0          Dinosaur Planet  2003–        NaN  14 Dec 2003   50 min  ...   
1                Character   1997          R  27 Mar 1998  122 min  ...   
2                     Sick   1997  Not Rated  07 Nov 1997   90 min  ...   
3                    8 Man   1992        NaN          NaN   83 min  ...   
4                  Fighter   2007        NaN  14 Dec 2007  100 min  ...   
...                    ...    ...        ...          ...      ...  ...   
12375            Interiors   1978         PG  06 Oct 1978   92 min  ...   
12376  Shakespeare in Love   1998          R  08 Jan 1999  123 min  ...   
12377                Epoch   2001      PG-13  24 Nov 2001   96 min  ...   
12378          The Company   2003      PG-13  20 May 2004  112 min  ...   
12379         Alien Hunter   2003          R  19 Jul 2003   92 min  ...   

      totalSeasons Response Error          DVD     BoxOffice  \
0              NaN     True   NaN          NaN           NaN   
1              NaN     True   NaN  04 Feb 2003      $623,983   
2              NaN     True   NaN  15 Feb 2017      $116,806   
3              NaN     True   NaN          NaN           NaN   
4              NaN     True   NaN          NaN           NaN   
...            ...      ...   ...          ...           ...   
12375          NaN     True   NaN  02 Feb 2017   $10,432,366   
12376          NaN     True   NaN  21 Apr 2016  $100,317,794   
12377          NaN     True   NaN  25 Jan 2017           NaN   
12378          NaN     True   NaN  16 Apr 2012    $2,283,914   
12379          NaN     True   NaN  20 Apr 2013           NaN   

                                              Production Website  \
0                                                    NaN     NaN   
1                                          Almerica Film     NaN   
2      Sick-the Life and Death of Bob Flanagan-Superm...     NaN   
3                                                    NaN     NaN   
4                                     First Run Features     NaN   
...                                                  ...     ...   
12375                          Rollins-Joffe Productions     NaN   
12376  Miramax Films, Bedford Falls Productions, Univ...     NaN   
12377                                Metro-Goldwyn-Mayer     NaN   
12378  First Snow Production, Capitol Films, Sandcast...     NaN   
12379                                                NaN     NaN   

      Rotten Tomatoes Metacritic  Ratings  
0                 NaN        NaN      NaN  
1                 92%        NaN      NaN  
2                 91%     82/100      NaN  
3                 NaN        NaN      NaN  
4                 NaN        NaN      NaN  
...               ...        ...      ...  
12375             79%     67/100      NaN  
12376             92%     87/100      NaN  
12377             16%        NaN      NaN  
12378             72%     73/100      NaN  
12379             16%        NaN      NaN  

[12380 rows x 34 columns]

In [12]:
df_250_train = pd.read_csv("./../raw_data/250_train.csv")
df_250_train

movie_id  Year_x                        Name      mean  count  \
0        5296  2003.0                        Camp  2.982863   6419   
1       12062  2002.0  The Wiggles: Wiggly Safari  3.333333    123   
2       16079  2003.0                 Dark Waters  2.269091    275   
3       11023  1998.0            Bubblegum Crisis  3.704156    409   
4        2013  2002.0                  Borderline  2.955846   1223   
..        ...     ...                         ...       ...    ...   
143      4278  1995.0              Miami Rhapsody  2.860560   1714   
144      4791  1940.0                   Pinocchio  3.614729   1290   
145     15651  1997.0                Oliver Twist  3.479549    709   
146     15869  1940.0     Broadway Melody of 1940  3.630499    682   
147     14255  1994.0                 Yeh Dillagi  2.918919    185   

                          Title     Year_y      Rated     Released  Runtime  \
0                          Camp       2003      PG-13  29 Aug 2003  114 min   
1    The Wiggles: Wiggly Safari       2002  Not Rated  03 Sep 2002   52 min   
2                   Dark Waters       2019      PG-13  06 Dec 2019  126 min   
3              Bubblegum Crisis  1987–1991      TV-MA  10 Dec 2014   25 min   
4                    Borderline       1980         PG  05 Mar 1981   97 min   
..                          ...        ...        ...          ...      ...   
143              Miami Rhapsody       1995      PG-13  27 Jan 1995   95 min   
144                   Pinocchio       1940          G  23 Feb 1940   88 min   
145                Oliver Twist       2005      PG-13  30 Sep 2005  130 min   
146     Broadway Melody of 1940       1940     Passed  09 Feb 1940  102 min   
147                 Yeh Dillagi       1994  Not Rated  06 May 1994  155 min   

     ...    BoxOffice                             Production Website Response  \
0    ...   $1,629,862                                    NaN     NaN     True   
1    ...          NaN                                    NaN     NaN     True   
2    ...  $11,136,084        Killer Films, Participant Media     NaN     True   
3    ...          NaN                                    NaN     NaN     True   
4    ...          NaN  Incorporated Television Company (ITC)     NaN     True   
..   ...          ...                                    ...     ...      ...   
143  ...   $5,221,281                     Hollywood Pictures     NaN     True   
144  ...  $84,254,167                Walt Disney Productions     NaN     True   
145  ...   $2,080,321                                    NaN     NaN     True   
146  ...          NaN   Metro-Goldwyn-Mayer, Loew&#39;s Inc.     NaN     True   
147  ...          NaN                         Yash Raj Films     NaN     True   

    Internet Movie Database Rotten Tomatoes Metacritic Error totalSeasons  \
0                    6.2/10             64%     55/100   NaN          NaN   
1                    6.6/10             NaN        NaN   NaN          NaN   
2                    7.6/10             89%     73/100   NaN          NaN   
3                    7.4/10             91%        NaN   NaN          1.0   
4                    6.0/10             33%        NaN   NaN          NaN   
..                      ...             ...        ...   ...          ...   
143                  5.4/10             45%        NaN   NaN          NaN   
144                  7.4/10             73%     99/100   NaN          NaN   
145                  6.8/10             NaN     65/100   NaN          NaN   
146                  7.3/10             80%        NaN   NaN          NaN   
147                  6.0/10             47%        NaN   NaN          NaN   

     Ratings  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
..       ...  
143      NaN  
144      NaN  
145      NaN  
146      NaN  
147      NaN  

[148 rows x 35 columns]

In [13]:
df_250_train.columns


Index(['movie_id', 'Year_x', 'Name', 'mean', 'count', 'Title', 'Year_y',
       'Rated', 'Released', 'Runtime', 'Genre', 'Director', 'Writer', 'Actors',
       'Plot', 'Language', 'Country', 'Awards', 'Poster', 'Metascore',
       'imdbRating', 'imdbVotes', 'imdbID', 'Type', 'DVD', 'BoxOffice',
       'Production', 'Website', 'Response', 'Internet Movie Database',
       'Rotten Tomatoes', 'Metacritic', 'Error', 'totalSeasons', 'Ratings'],
      dtype='object')

In [28]:
df_250_train.Actors[0]

'Don Dixon, Daniel Letterle, Joanna Chilcoat'

In [23]:
actors = df_250_train["Actors"]

vectorizer = CountVectorizer(max_features=2)

X = vectorizer.fit_transform(actors)

print(vectorizer.get_feature_names())

['david', 'james']


In [30]:
vectorizer = CountVectorizer(token_pattern=r"^\w\s\w\W$")

X = vectorizer.fit_transform(actors)

print(vectorizer.get_feature_names())


ValueError: empty vocabulary; perhaps the documents only contain stop words

In [24]:
print(X.toarray())
print(X.toarray().shape)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [2 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]

In [25]:

print(vectorizer.get_feature_names())
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
>>> print(X.toarray())
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
>>> vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
>>> X2 = vectorizer2.fit_transform(corpus)
>>> print(vectorizer2.get_feature_names())
['and this', 'document is', 'first document', 'is the', 'is this',
'second document', 'the first', 'the second', 'the third', 'third one',
 'this document', 'this is', 'this the']
 >>> print(X2.toarray())
 [[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]

SyntaxError: invalid syntax (<ipython-input-25-aa2953a625a7>, line 3)