# Regex - loading the data 

In [63]:
import requests
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer


In [64]:
ls


 PriscillaDay3AM.ipynb             Priscilla - exploring Regex.ipynb
David.ipynb                        Priscilla -API fetching .ipynb
Davis-Pris API.ipynb               Untitled.ipynb
Pris-  exploring actors.ipynb      Untitled1.ipynb
Pris- exploring genres.ipynb       renato_call_data.ipynb


In [65]:
full_data_merged = pd.read_csv("./../raw_data/merged_movies_by_index.csv")
full_data_merged

avg_review_score  n_reviews  year                 title  \
0              3.749543        547  2003       Dinosaur Planet   
1              3.641153       2012  1997             Character   
2              3.084396       1019  1997                  Sick   
3              2.129032         93  1992                 8 Man   
4              3.417582        546  1947  My Favorite Brunette   
...                 ...        ...   ...                   ...   
10381          3.411855       1957  1978             Interiors   
10382          3.867112      64957  1998   Shakespeare in Love   
10383          2.839207       1362  2000                 Epoch   
10384          2.498592       6749  2003           The Company   
10385          2.816504        921  2003          Alien Hunter   

                      Title  Year      Rated     Released  Runtime  \
0           Dinosaur Planet  2003        NaN  14 Dec 2003   50 min   
1                 Character  1997          R  27 Mar 1998  122 min   
2                      Sick  1997  Not Rated  07 Nov 1997   90 min   
3                     8 Man  1992        NaN          NaN   83 min   
4      My Favorite Brunette  1947     Passed  04 Apr 1947   87 min   
...                     ...   ...        ...          ...      ...   
10381             Interiors  1978         PG  06 Oct 1978   92 min   
10382   Shakespeare in Love  1998          R  08 Jan 1999  123 min   
10383                 Epoch  2001      PG-13  24 Nov 2001   96 min   
10384           The Company  2003      PG-13  20 May 2004  112 min   
10385          Alien Hunter  2003          R  19 Jul 2003   92 min   

                                           Genre  ... Response  \
0                 Documentary, Animation, Family  ...     True   
1                          Crime, Drama, Mystery  ...     True   
2                                    Documentary  ...     True   
3                                 Action, Sci-Fi  ...     True   
4      Comedy, Crime, Mystery, Romance, Thriller  ...     True   
...                                          ...  ...      ...   
10381                                      Drama  ...     True   
10382            Comedy, Drama, History, Romance  ...     True   
10383                           Sci-Fi, Thriller  ...     True   
10384                      Drama, Music, Romance  ...     True   
10385                  Action, Adventure, Sci-Fi  ...     True   

      Internet Movie Database Index_match          DVD     BoxOffice  \
0                      7.7/10           1          NaN           NaN   
1                      7.7/10           3  04 Feb 2003      $623,983   
2                      7.5/10           6  15 Feb 2017      $116,806   
3                      5.4/10           7          NaN           NaN   
4                      6.8/10          12  10 Mar 2016           NaN   
...                       ...         ...          ...           ...   
10381                  7.4/10       17763  02 Feb 2017   $10,432,366   
10382                  7.1/10       17764  21 Apr 2016  $100,317,794   
10383                  5.0/10       17768  25 Jan 2017           NaN   
10384                  6.3/10       17769  16 Apr 2012    $2,283,914   
10385                  5.1/10       17770  20 Apr 2013           NaN   

                                              Production Website  \
0                                                    NaN     NaN   
1                                          Almerica Film     NaN   
2      Sick-the Life and Death of Bob Flanagan-Superm...     NaN   
3                                                    NaN     NaN   
4                   Paramount Pictures, Hope Enterprises     NaN   
...                                                  ...     ...   
10381                          Rollins-Joffe Productions     NaN   
10382  Miramax Films, Bedford Falls Productions, Univ...     NaN   
10383                                Metro-Goldwyn-Mayer     NaN   
10384  First Snow Production, Capit

In [79]:
full_data_merged.columns

Index(['avg_review_score', 'n_reviews', 'year', 'title', 'Title', 'Year',
       'Rated', 'Released', 'Runtime', 'Genre', 'Director', 'Writer', 'Actors',
       'Plot', 'Language', 'Country', 'Awards', 'Poster', 'Metascore',
       'imdbRating', 'imdbVotes', 'imdbID', 'Type', 'totalSeasons', 'Response',
       'Internet Movie Database', 'Index_match', 'DVD', 'BoxOffice',
       'Production', 'Website', 'Rotten Tomatoes', 'Metacritic', 'Ratings'],
      dtype='object')

# Regex for Genre

In [77]:
genre = full_data_merged["Genre"].fillna("")

# vectorizer = CountVectorizer(max_features=2)

# X = vectorizer.fit_transform(genre)

# print(vectorizer.get_feature_names())

In [94]:
vectorizer = CountVectorizer(token_pattern="[a-zA-Z][a-z -]+", max_features=5)

X = vectorizer.fit_transform(genre)

print(vectorizer.get_feature_names())


['action', 'comedy', 'drama', 'romance', 'thriller']


In [93]:
print(X.toarray())
print(X.toarray().shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]]
(10386, 28)


In [72]:
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

comedy  drama
0           0      0
1           0      1
2           0      0
3           0      0
4           1      0
...       ...    ...
10381       0      1
10382       1      1
10383       0      0
10384       0      1
10385       0      0

[10386 rows x 2 columns]

In [73]:
full_data_merged.join(pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names()))

avg_review_score  n_reviews  year                 title  \
0              3.749543        547  2003       Dinosaur Planet   
1              3.641153       2012  1997             Character   
2              3.084396       1019  1997                  Sick   
3              2.129032         93  1992                 8 Man   
4              3.417582        546  1947  My Favorite Brunette   
...                 ...        ...   ...                   ...   
10381          3.411855       1957  1978             Interiors   
10382          3.867112      64957  1998   Shakespeare in Love   
10383          2.839207       1362  2000                 Epoch   
10384          2.498592       6749  2003           The Company   
10385          2.816504        921  2003          Alien Hunter   

                      Title  Year      Rated     Released  Runtime  \
0           Dinosaur Planet  2003        NaN  14 Dec 2003   50 min   
1                 Character  1997          R  27 Mar 1998  122 min   
2                      Sick  1997  Not Rated  07 Nov 1997   90 min   
3                     8 Man  1992        NaN          NaN   83 min   
4      My Favorite Brunette  1947     Passed  04 Apr 1947   87 min   
...                     ...   ...        ...          ...      ...   
10381             Interiors  1978         PG  06 Oct 1978   92 min   
10382   Shakespeare in Love  1998          R  08 Jan 1999  123 min   
10383                 Epoch  2001      PG-13  24 Nov 2001   96 min   
10384           The Company  2003      PG-13  20 May 2004  112 min   
10385          Alien Hunter  2003          R  19 Jul 2003   92 min   

                                           Genre  ... Index_match  \
0                 Documentary, Animation, Family  ...           1   
1                          Crime, Drama, Mystery  ...           3   
2                                    Documentary  ...           6   
3                                 Action, Sci-Fi  ...           7   
4      Comedy, Crime, Mystery, Romance, Thriller  ...          12   
...                                          ...  ...         ...   
10381                                      Drama  ...       17763   
10382            Comedy, Drama, History, Romance  ...       17764   
10383                           Sci-Fi, Thriller  ...       17768   
10384                      Drama, Music, Romance  ...       17769   
10385                  Action, Adventure, Sci-Fi  ...       17770   

               DVD     BoxOffice  \
0              NaN           NaN   
1      04 Feb 2003      $623,983   
2      15 Feb 2017      $116,806   
3              NaN           NaN   
4      10 Mar 2016           NaN   
...            ...           ...   
10381  02 Feb 2017   $10,432,366   
10382  21 Apr 2016  $100,317,794   
10383  25 Jan 2017           NaN   
10384  16 Apr 2012    $2,283,914   
10385  20 Apr 2013           NaN   

                                              Production Website  \
0                                                    NaN     NaN   
1                                          Almerica Film     NaN   
2      Sick-the Life and Death of Bob Flanagan-Superm...     NaN   
3                                                    NaN     NaN   
4                   Paramount Pictures, Hope Enterprises     NaN   
...                                                  ...     ...   
10381                          Rollins-Joffe Productions     NaN   
10382  Miramax Films, Bedford Falls Productions, Univ...     NaN   
10383                                Metro-Goldwyn-Mayer     NaN   
10384  First Snow Production, Capitol Films, Sandcast...     NaN   
10385                                                NaN     NaN   

      Rotten Tomatoes Metacritic Ratings  comedy  drama  
0                 NaN        NaN     NaN       0      0  
1                 92%        NaN     NaN       0      1  
2                 91%     82/100     NaN       0      0  
3                 NaN        NaN     NaN       0      0  
4   

In [105]:
full_data_merged = full_data_merged.fillna("")
full_data_merged[full_data_merged["Director"].str.contains("co-director")]["Director"]

16              Phil Robinson, David Marshall(co-director)
26                     Sam Green, Bill Siegel(co-director)
1152     John Alan Schwartz, Susumu Saegusa(co-director...
1611                Jackie Cockle, Sarah Ball(co-director)
2063                Steve Bannon, Tim Watkins(co-director)
2183        E.V.V. Satyanarayana, Pranavanand(co-director)
2466            Ahathian, Sunil Kumar Agrawal(co-director)
2607                            Dale S. Lewis(co-director)
2614            Kazuki Akane, Yoshiyuki Takei(co-director)
2839            Chris Delaporte, Pascal Pinon(co-director)
2997     Olivier Ducastel(co-director), Jacques Martine...
3033                  Po Johns, Howard Gibson(co-director)
3061             José Padilha, Felipe Lacerda(co-director)
3340                            Dale S. Lewis(co-director)
3465             Matthew Carnahan, John Philp(co-director)
3785           Fernando Meirelles, Kátia Lund(co-director)
3817            John Lasseter, Andrew Stanton(co-directo

# Regex for actors 

In [82]:
actores = full_data_merged["Actors"].fillna("")

vectorizer = CountVectorizer(token_pattern="[a-zA-Z][a-z -]+", max_features=10)

X = vectorizer.fit_transform(actors)

print(vectorizer.get_feature_names())

# print(X.toarray())



['eric roberts', 'james woods', 'kirsten dunst', 'mia farrow', 'mickey rourke', 'nick nolte', 'shirley maclaine', 'sidney poitier', 'susan sarandon', 'tobey maguire']


In [83]:
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

eric roberts  james woods  kirsten dunst  mia farrow  mickey rourke  \
0               0            0              0           0              0   
1               0            0              0           0              0   
2               0            0              0           0              0   
3               0            0              0           0              0   
4               0            0              0           0              0   
..            ...          ...            ...         ...            ...   
143             0            0              0           1              0   
144             0            0              0           0              0   
145             0            0              0           0              0   
146             0            0              0           0              0   
147             0            0              0           0              0   

     nick nolte  shirley maclaine  sidney poitier  susan sarandon  \
0             0                 0               0               0   
1             0                 0               0               0   
2             0                 0               0               0   
3             0                 0               0               0   
4             0                 0               0               0   
..          ...               ...             ...             ...   
143           0                 0               0               0   
144           0                 0               0               0   
145           0                 0               0               0   
146           0                 0               0               0   
147           0                 0               0               0   

     tobey maguire  
0                0  
1                0  
2                0  
3                0  
4                0  
..             ...  
143              0  
144              0  
145              0  
146              0  
147              0  

[148 rows x 10 columns]

In [84]:
full_data_merged.join(pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names()))

avg_review_score  n_reviews  year                 title  \
0              3.749543        547  2003       Dinosaur Planet   
1              3.641153       2012  1997             Character   
2              3.084396       1019  1997                  Sick   
3              2.129032         93  1992                 8 Man   
4              3.417582        546  1947  My Favorite Brunette   
...                 ...        ...   ...                   ...   
10381          3.411855       1957  1978             Interiors   
10382          3.867112      64957  1998   Shakespeare in Love   
10383          2.839207       1362  2000                 Epoch   
10384          2.498592       6749  2003           The Company   
10385          2.816504        921  2003          Alien Hunter   

                      Title  Year      Rated     Released  Runtime  \
0           Dinosaur Planet  2003        NaN  14 Dec 2003   50 min   
1                 Character  1997          R  27 Mar 1998  122 min   
2                      Sick  1997  Not Rated  07 Nov 1997   90 min   
3                     8 Man  1992        NaN          NaN   83 min   
4      My Favorite Brunette  1947     Passed  04 Apr 1947   87 min   
...                     ...   ...        ...          ...      ...   
10381             Interiors  1978         PG  06 Oct 1978   92 min   
10382   Shakespeare in Love  1998          R  08 Jan 1999  123 min   
10383                 Epoch  2001      PG-13  24 Nov 2001   96 min   
10384           The Company  2003      PG-13  20 May 2004  112 min   
10385          Alien Hunter  2003          R  19 Jul 2003   92 min   

                                           Genre  ... eric roberts  \
0                 Documentary, Animation, Family  ...          0.0   
1                          Crime, Drama, Mystery  ...          0.0   
2                                    Documentary  ...          0.0   
3                                 Action, Sci-Fi  ...          0.0   
4      Comedy, Crime, Mystery, Romance, Thriller  ...          0.0   
...                                          ...  ...          ...   
10381                                      Drama  ...          NaN   
10382            Comedy, Drama, History, Romance  ...          NaN   
10383                           Sci-Fi, Thriller  ...          NaN   
10384                      Drama, Music, Romance  ...          NaN   
10385                  Action, Adventure, Sci-Fi  ...          NaN   

      james woods kirsten dunst mia farrow mickey rourke nick nolte  \
0             0.0           0.0        0.0           0.0        0.0   
1             0.0           0.0        0.0           0.0        0.0   
2             0.0           0.0        0.0           0.0        0.0   
3             0.0           0.0        0.0           0.0        0.0   
4             0.0           0.0        0.0           0.0        0.0   
...           ...           ...        ...           ...        ...   
10381         NaN           NaN        NaN           NaN        NaN   
10382         NaN           NaN        NaN           NaN        NaN   
10383         NaN           NaN        NaN           NaN        NaN   
10384         NaN           NaN        NaN           NaN        NaN   
10385         NaN           NaN        NaN           NaN        NaN   

      shirley maclaine sidney poitier  susan sarandon  tobey maguire  
0                  0.0            0.0             0.0            0.0  
1                  0.0            0.0             0.0            0.0  
2                  0.0            0.0             0.0            0.0  
3                  0.0            0.0             0.0            0.0  
4                  0.0            0.0             0.0            0.0  
...                ...            ...             ...            ...  
10381              NaN            NaN             NaN            NaN  
10382              NaN            NaN             NaN            NaN  
10383              NaN            NaN   

# Regex for Director

In [98]:
director = full_data_merged["Director"].fillna("")

vectorizer = CountVectorizer(token_pattern="[a-zA-Z][a-z -]+", max_features=6)

X = vectorizer.fit_transform(director)

print(vectorizer.get_feature_names())

['alfred hitchcock', 'clint eastwood', 'co-director', 'jim wynorski', 'steven spielberg', 'woody allen']


In [99]:
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

alfred hitchcock  clint eastwood  co-director  jim wynorski  \
0                     0               0            0             0   
1                     0               0            0             0   
2                     0               0            0             0   
3                     0               0            0             0   
4                     0               0            0             0   
...                 ...             ...          ...           ...   
10381                 0               0            0             0   
10382                 0               0            0             0   
10383                 0               0            0             0   
10384                 0               0            0             0   
10385                 0               0            0             0   

       steven spielberg  woody allen  
0                     0            0  
1                     0            0  
2                     0            0  
3                     0            0  
4                     0            0  
...                 ...          ...  
10381                 0            1  
10382                 0            0  
10383                 0            0  
10384                 0            0  
10385                 0            0  

[10386 rows x 6 columns]

In [97]:
full_data_merged.join(pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names()))

avg_review_score  n_reviews  year                 title  \
0              3.749543        547  2003       Dinosaur Planet   
1              3.641153       2012  1997             Character   
2              3.084396       1019  1997                  Sick   
3              2.129032         93  1992                 8 Man   
4              3.417582        546  1947  My Favorite Brunette   
...                 ...        ...   ...                   ...   
10381          3.411855       1957  1978             Interiors   
10382          3.867112      64957  1998   Shakespeare in Love   
10383          2.839207       1362  2000                 Epoch   
10384          2.498592       6749  2003           The Company   
10385          2.816504        921  2003          Alien Hunter   

                      Title  Year      Rated     Released  Runtime  \
0           Dinosaur Planet  2003        NaN  14 Dec 2003   50 min   
1                 Character  1997          R  27 Mar 1998  122 min   
2                      Sick  1997  Not Rated  07 Nov 1997   90 min   
3                     8 Man  1992        NaN          NaN   83 min   
4      My Favorite Brunette  1947     Passed  04 Apr 1947   87 min   
...                     ...   ...        ...          ...      ...   
10381             Interiors  1978         PG  06 Oct 1978   92 min   
10382   Shakespeare in Love  1998          R  08 Jan 1999  123 min   
10383                 Epoch  2001      PG-13  24 Nov 2001   96 min   
10384           The Company  2003      PG-13  20 May 2004  112 min   
10385          Alien Hunter  2003          R  19 Jul 2003   92 min   

                                           Genre  ...  \
0                 Documentary, Animation, Family  ...   
1                          Crime, Drama, Mystery  ...   
2                                    Documentary  ...   
3                                 Action, Sci-Fi  ...   
4      Comedy, Crime, Mystery, Romance, Thriller  ...   
...                                          ...  ...   
10381                                      Drama  ...   
10382            Comedy, Drama, History, Romance  ...   
10383                           Sci-Fi, Thriller  ...   
10384                      Drama, Music, Romance  ...   
10385                  Action, Adventure, Sci-Fi  ...   

                                              Production Website  \
0                                                    NaN     NaN   
1                                          Almerica Film     NaN   
2      Sick-the Life and Death of Bob Flanagan-Superm...     NaN   
3                                                    NaN     NaN   
4                   Paramount Pictures, Hope Enterprises     NaN   
...                                                  ...     ...   
10381                          Rollins-Joffe Productions     NaN   
10382  Miramax Films, Bedford Falls Productions, Univ...     NaN   
10383                                Metro-Goldwyn-Mayer     NaN   
10384  First Snow Production, Capitol Films, Sandcast...     NaN   
10385                                                NaN     NaN   

      Rotten Tomatoes Metacritic Ratings alfred hitchcock clint eastwood  \
0                 NaN        NaN     NaN                0              0   
1                 92%        NaN     NaN                0              0   
2                 91%     82/100     NaN                0              0   
3                 NaN        NaN     NaN                0              0   
4                 75%        NaN     NaN                0              0   
...               ...        ...     ...              ...            ...   
10381             79%     67/100     NaN                0              0   
10382             92%     87/100     NaN                0              0   
10383             16%        NaN     NaN                0              0   
10384             72%     73/100     NaN                0              0   
10385             16%        NaN   